app:
  image: uptownhr/christina-grimmie
  environment:
  - VIRTUAL_HOST=christinagrimmieforever.com
proxy:
  image: jwilder/nginx-proxy
  ports:
  - "80:80"
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro